// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB3PcAECeXHsqYBxbJpIVAxRrsbHrfGpc',
    appId: '1:472711786412:web:e5fb5dcfdfb52c3be35409',
    messagingSenderId: '472711786412',
    projectId: 'photo-hub-211ae',
    authDomain: 'photo-hub-211ae.firebaseapp.com',
    storageBucket: 'photo-hub-211ae.appspot.com',
    measurementId: 'G-8PT4JY2TY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvHHfokwnX3_C_5w5b0BbTuAqc3FclrRI',
    appId: '1:472711786412:android:5deb2861d6f94416e35409',
    messagingSenderId: '472711786412',
    projectId: 'photo-hub-211ae',
    storageBucket: 'photo-hub-211ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA11ctCT4lTx54wdcsIXM0sNx_MFTUAkKo',
    appId: '1:472711786412:ios:8c77247595687421e35409',
    messagingSenderId: '472711786412',
    projectId: 'photo-hub-211ae',
    storageBucket: 'photo-hub-211ae.appspot.com',
    iosBundleId: 'com.example.photoHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA11ctCT4lTx54wdcsIXM0sNx_MFTUAkKo',
    appId: '1:472711786412:ios:8c77247595687421e35409',
    messagingSenderId: '472711786412',
    projectId: 'photo-hub-211ae',
    storageBucket: 'photo-hub-211ae.appspot.com',
    iosBundleId: 'com.example.photoHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB3PcAECeXHsqYBxbJpIVAxRrsbHrfGpc',
    appId: '1:472711786412:web:908dbbb8249d6345e35409',
    messagingSenderId: '472711786412',
    projectId: 'photo-hub-211ae',
    authDomain: 'photo-hub-211ae.firebaseapp.com',
    storageBucket: 'photo-hub-211ae.appspot.com',
    measurementId: 'G-YXK526SSWE',
  );
}
